### ISSUE TITLE
Extinguishing fires with the water cannon only works in the editor and not in a build

### ISSUE THREAD

**Issue by Mitchell-T** [AlexJanson/LekAanDek#40]
The water cannon does not function properly in a built version of the game which makes the builds unable to be finished by the player

## Expected Behavior
Fire is extinguished when fired upon by the water cannon.

## Current Behavior
Fire is only extinguished in the editor but not in a build

## Possible Solution
needs further investigation

## Steps to Reproduce
1. build the game
2. fire the water cannon at the fires
3. fire doesn't extinguish

**Comment by AlexJanson** [comment]
Fixed with #50
