### ISSUE TITLE
The game can't be played after a restart

### ISSUE THREAD

**Issue by SjorsMaster** [AlexJanson/LekAanDek#53]
An issue with the intro explaination from the captain where the game doesn't progresses due to an error.

## Expected Behavior
The game restarting normally

## Current Behavior
An error appears when starting the intro after a restart which results in the captain that stops talking 

## Possible Solution
Needs further investigation

## Steps to Reproduce

1. Start the game in editor
2. Wait for the captain to be done with talking
3. Restart the scene through menu in vr or activate button through editor (see steps below)
4. An error should appear

Steps on desktop (Non VR):
![image](https://user-images.githubusercontent.com/39805109/119117809-e5fe3600-ba29-11eb-9ea5-3b6979934710.png)

**Comment by Mitchell-T** [comment]
Fixed in #55
